<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20240506183728 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial migration for creating pairs and rates tables.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQLPlatform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQLPlatform'."
        );

        $this->addSql('CREATE TABLE pairs (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
            date DATE DEFAULT NULL, 
            code VARCHAR(3) NOT NULL, 
            rate DECIMAL(16, 8) NOT NULL, 
            currency VARCHAR(3) NOT NULL, 
            PRIMARY KEY(id))'
        );
        $this->addSql('CREATE UNIQUE INDEX uniq_pairs_code_currency_key ON pairs(code, currency)');

        $this->addSql('CREATE TABLE rates (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
            date DATE NOT NULL, 
            code VARCHAR(3) NOT NULL, 
            rate DECIMAL(16, 8) NOT NULL, 
            currency VARCHAR(3) NOT NULL, 
            PRIMARY KEY(id))'
        );
        $this->addSql('CREATE UNIQUE INDEX uniq_44d4ab3caa9e377a771530986956883f ON rates (date, code, currency)');
        $this->addSql('CREATE INDEX idx_44d4ab3c6956883f ON rates (currency)');
        $this->addSql('CREATE INDEX idx_44d4ab3c77153098 ON rates (code)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE pairs');
        $this->addSql('DROP TABLE rates');
    }
}
