# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Command\ConvertCurrencyCommand:
        tags:
            - { name: 'console.command', command: 'currency:convert' }

    App\Command\ImportRatesCommand:
        tags:
            - { name: 'console.command', command: 'rates:import' }

    App\Provider\EcbRatesProvider:
        arguments:
            $url: '%env(ECB_URL)%'
            $code: '%env(ECB_CODE)%'
        tags: [ 'app.rates_provider' ]

    App\Provider\CoinDeskRatesProvider:
        arguments:
            $url: '%env(COINDESK_URL)%'
            $code: '%env(COINDESK_CODE)%'
        tags: [ 'app.rates_provider' ]

    App\Service\Rate\RatesImporter:
        arguments:
            - !tagged_iterator app.rates_provider
